title:              Hussein Adi - Software Developer
tagline:             'Software Developer'
description:          'A description for Software Developer'
url:                 "https://husseinadi.com"
baseurl:             ''

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

sass:
  style: compressed

kramdown:
  auto_ids: true
  input: GFM
